apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  clusterIP: None
  selector:
    app: grpc-server
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: probes
      port: 9091
      targetPort: probes
